### ISSUE TITLE
Ammo shouldn't need to be set to 0 on weapon reload

### ISSUE THREAD

**Issue by Shinigami92** [Shinigami92/sturdy-adventure#16]
https://github.com/Shinigami92/sturdy-adventure/blob/493d9018aea86279a70b0bfb4d691ecf5486c7e7/src/entities/weapons/weapon.ts#L66-L67

It would be much better for the player experience when the player reloads they can see how many ammo was left in the clip.
Also if e.g. a shotgun would be implemented, it could reload each ammo one by one instead of full clip. This would not work at all with the current implementation.

**Comment by ST-DDT** [comment]
Instead of keeping it at zero if the ammo isn't reloading, you can keep it at `+Inf` because `+Inf - 1 = +Inf`.
